import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manual sidebar configuration with sections
  docsSidebar: [
    // Overview at the top
    {
      type: 'doc',
      id: 'devdocs/overview',
      label: 'Overview',
    },
    
    // Builders section heading
    {
      type: 'html',
      value: '<span class="sidebar-section-title">#BUIDLers</span>',
      className: 'sidebar-section-header',
    },
    
    // Builders section items
    {
      type: 'category',
      label: 'Quick Start',
      link: {
        type: 'generated-index',
        description: 'Get started with CoFHE',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'devdocs/quick-start',
        },
      ],
    },
    {
      type: 'category',
      label: 'CoFHE.JS',
      link: {
        type: 'generated-index',
        description: 'JavaScript SDK for CoFHE',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'devdocs/cofhejs',
        },
      ],
    },
    {
      type: 'category',
      label: 'FHE Library',
      link: {
        type: 'generated-index',
        description: 'Core FHE functionality',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'devdocs/fhe-library',
        },
      ],
    },
    {
      type: 'category',
      label: 'FHERC',
      link: {
        type: 'generated-index',
        description: 'FHE token standards',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'devdocs/fherc',
        },
      ],
    },
    {
      type: 'category',
      label: 'SolidityAPI',
      link: {
        type: 'generated-index',
        description: 'Solidity API reference',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'devdocs/solidity-api',
        },
      ],
    },
    {
      type: 'doc',
      id: 'devdocs/sdk/index',
      label: 'SDK',
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'generated-index',
        description: 'Learn by example',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'devdocs/tutorials',
        },
      ],
    },
    {
      type: 'category',
      label: 'Pay Attention',
      link: {
        type: 'generated-index',
        description: 'Important notices',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'devdocs/pay-attention',
        },
      ],
    },
    
    // Deep Dive section heading
    {
      type: 'html',
      value: '<span class="sidebar-section-title">Deep Dive</span>',
      className: 'sidebar-section-header',
    },
    
    // Deep Dive section items
    {
      type: 'category',
      label: 'Architecture',
      link: {
        type: 'generated-index',
        description: 'CoFHE Architecture',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'devdocs/architecture',
        },
      ],
    },
    {
      type: 'doc',
      id: 'devdocs/future-plans',
      label: 'Future Plans',
    },
    {
      type: 'doc',
      id: 'devdocs/research-and-publications',
      label: 'Research in Fhenix',
    },
  ],
  // tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
